//go:build go1.16
// +build go1.16

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package azurespecialsgroup

import "net/http"

// APIVersionDefaultGetMethodGlobalNotProvidedValidResponse contains the response from method APIVersionDefault.GetMethodGlobalNotProvidedValid.
type APIVersionDefaultGetMethodGlobalNotProvidedValidResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// APIVersionDefaultGetMethodGlobalValidResponse contains the response from method APIVersionDefault.GetMethodGlobalValid.
type APIVersionDefaultGetMethodGlobalValidResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// APIVersionDefaultGetPathGlobalValidResponse contains the response from method APIVersionDefault.GetPathGlobalValid.
type APIVersionDefaultGetPathGlobalValidResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// APIVersionDefaultGetSwaggerGlobalValidResponse contains the response from method APIVersionDefault.GetSwaggerGlobalValid.
type APIVersionDefaultGetSwaggerGlobalValidResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// APIVersionLocalGetMethodLocalNullResponse contains the response from method APIVersionLocal.GetMethodLocalNull.
type APIVersionLocalGetMethodLocalNullResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// APIVersionLocalGetMethodLocalValidResponse contains the response from method APIVersionLocal.GetMethodLocalValid.
type APIVersionLocalGetMethodLocalValidResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// APIVersionLocalGetPathLocalValidResponse contains the response from method APIVersionLocal.GetPathLocalValid.
type APIVersionLocalGetPathLocalValidResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// APIVersionLocalGetSwaggerLocalValidResponse contains the response from method APIVersionLocal.GetSwaggerLocalValid.
type APIVersionLocalGetSwaggerLocalValidResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// HeaderCustomNamedRequestIDHeadResponse contains the response from method Header.CustomNamedRequestIDHead.
type HeaderCustomNamedRequestIDHeadResponse struct {
	HeaderCustomNamedRequestIDHeadResult
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// HeaderCustomNamedRequestIDHeadResult contains the result from method Header.CustomNamedRequestIDHead.
type HeaderCustomNamedRequestIDHeadResult struct {
	// FooRequestID contains the information returned from the foo-request-id header response.
	FooRequestID *string

	// Success indicates if the operation succeeded or failed.
	Success bool
}

// HeaderCustomNamedRequestIDParamGroupingResponse contains the response from method Header.CustomNamedRequestIDParamGrouping.
type HeaderCustomNamedRequestIDParamGroupingResponse struct {
	HeaderCustomNamedRequestIDParamGroupingResult
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// HeaderCustomNamedRequestIDParamGroupingResult contains the result from method Header.CustomNamedRequestIDParamGrouping.
type HeaderCustomNamedRequestIDParamGroupingResult struct {
	// FooRequestID contains the information returned from the foo-request-id header response.
	FooRequestID *string
}

// HeaderCustomNamedRequestIDResponse contains the response from method Header.CustomNamedRequestID.
type HeaderCustomNamedRequestIDResponse struct {
	HeaderCustomNamedRequestIDResult
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// HeaderCustomNamedRequestIDResult contains the result from method Header.CustomNamedRequestID.
type HeaderCustomNamedRequestIDResult struct {
	// FooRequestID contains the information returned from the foo-request-id header response.
	FooRequestID *string
}

// ODataGetWithFilterResponse contains the response from method OData.GetWithFilter.
type ODataGetWithFilterResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// SkipURLEncodingGetMethodPathValidResponse contains the response from method SkipURLEncoding.GetMethodPathValid.
type SkipURLEncodingGetMethodPathValidResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// SkipURLEncodingGetMethodQueryNullResponse contains the response from method SkipURLEncoding.GetMethodQueryNull.
type SkipURLEncodingGetMethodQueryNullResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// SkipURLEncodingGetMethodQueryValidResponse contains the response from method SkipURLEncoding.GetMethodQueryValid.
type SkipURLEncodingGetMethodQueryValidResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// SkipURLEncodingGetPathQueryValidResponse contains the response from method SkipURLEncoding.GetPathQueryValid.
type SkipURLEncodingGetPathQueryValidResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// SkipURLEncodingGetPathValidResponse contains the response from method SkipURLEncoding.GetPathValid.
type SkipURLEncodingGetPathValidResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// SkipURLEncodingGetSwaggerPathValidResponse contains the response from method SkipURLEncoding.GetSwaggerPathValid.
type SkipURLEncodingGetSwaggerPathValidResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// SkipURLEncodingGetSwaggerQueryValidResponse contains the response from method SkipURLEncoding.GetSwaggerQueryValid.
type SkipURLEncodingGetSwaggerQueryValidResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// SubscriptionInCredentialsPostMethodGlobalNotProvidedValidResponse contains the response from method SubscriptionInCredentials.PostMethodGlobalNotProvidedValid.
type SubscriptionInCredentialsPostMethodGlobalNotProvidedValidResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// SubscriptionInCredentialsPostMethodGlobalNullResponse contains the response from method SubscriptionInCredentials.PostMethodGlobalNull.
type SubscriptionInCredentialsPostMethodGlobalNullResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// SubscriptionInCredentialsPostMethodGlobalValidResponse contains the response from method SubscriptionInCredentials.PostMethodGlobalValid.
type SubscriptionInCredentialsPostMethodGlobalValidResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// SubscriptionInCredentialsPostPathGlobalValidResponse contains the response from method SubscriptionInCredentials.PostPathGlobalValid.
type SubscriptionInCredentialsPostPathGlobalValidResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// SubscriptionInCredentialsPostSwaggerGlobalValidResponse contains the response from method SubscriptionInCredentials.PostSwaggerGlobalValid.
type SubscriptionInCredentialsPostSwaggerGlobalValidResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// SubscriptionInMethodPostMethodLocalNullResponse contains the response from method SubscriptionInMethod.PostMethodLocalNull.
type SubscriptionInMethodPostMethodLocalNullResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// SubscriptionInMethodPostMethodLocalValidResponse contains the response from method SubscriptionInMethod.PostMethodLocalValid.
type SubscriptionInMethodPostMethodLocalValidResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// SubscriptionInMethodPostPathLocalValidResponse contains the response from method SubscriptionInMethod.PostPathLocalValid.
type SubscriptionInMethodPostPathLocalValidResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// SubscriptionInMethodPostSwaggerLocalValidResponse contains the response from method SubscriptionInMethod.PostSwaggerLocalValid.
type SubscriptionInMethodPostSwaggerLocalValidResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// XMSClientRequestIDGetResponse contains the response from method XMSClientRequestID.Get.
type XMSClientRequestIDGetResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// XMSClientRequestIDParamGetResponse contains the response from method XMSClientRequestID.ParamGet.
type XMSClientRequestIDParamGetResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}
