// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package optionalitygroup

import (
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
)

// OptionalClient - Illustrates models with optional properties.
// Don't use this type directly, use NewOptionalClientWithNoCredential() instead.
type OptionalClient struct {
	internal *azcore.Client
	endpoint string
}

// OptionalClientOptions contains the optional values for creating a [OptionalClient].
type OptionalClientOptions struct {
	azcore.ClientOptions
}

// NewOptionalClientWithNoCredential creates a new instance of OptionalClient with the specified values.
//   - endpoint - Service host
//   - options - Contains optional client configuration. Pass nil to accept the default values.
func NewOptionalClientWithNoCredential(endpoint string, options *OptionalClientOptions) (*OptionalClient, error) {
	if options == nil {
		options = &OptionalClientOptions{}
	}
	cl, err := azcore.NewClient(moduleName, moduleVersion, runtime.PipelineOptions{}, &options.ClientOptions)
	if err != nil {
		return nil, err
	}
	client := &OptionalClient{
		endpoint: endpoint,
		internal: cl,
	}
	return client, nil
}

// NewOptionalBooleanLiteralClient creates a new instance of [OptionalBooleanLiteralClient].
func (client *OptionalClient) NewOptionalBooleanLiteralClient() *OptionalBooleanLiteralClient {
	return &OptionalBooleanLiteralClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewOptionalBytesClient creates a new instance of [OptionalBytesClient].
func (client *OptionalClient) NewOptionalBytesClient() *OptionalBytesClient {
	return &OptionalBytesClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewOptionalCollectionsByteClient creates a new instance of [OptionalCollectionsByteClient].
func (client *OptionalClient) NewOptionalCollectionsByteClient() *OptionalCollectionsByteClient {
	return &OptionalCollectionsByteClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewOptionalCollectionsModelClient creates a new instance of [OptionalCollectionsModelClient].
func (client *OptionalClient) NewOptionalCollectionsModelClient() *OptionalCollectionsModelClient {
	return &OptionalCollectionsModelClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewOptionalDatetimeClient creates a new instance of [OptionalDatetimeClient].
func (client *OptionalClient) NewOptionalDatetimeClient() *OptionalDatetimeClient {
	return &OptionalDatetimeClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewOptionalDurationClient creates a new instance of [OptionalDurationClient].
func (client *OptionalClient) NewOptionalDurationClient() *OptionalDurationClient {
	return &OptionalDurationClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewOptionalFloatLiteralClient creates a new instance of [OptionalFloatLiteralClient].
func (client *OptionalClient) NewOptionalFloatLiteralClient() *OptionalFloatLiteralClient {
	return &OptionalFloatLiteralClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewOptionalIntLiteralClient creates a new instance of [OptionalIntLiteralClient].
func (client *OptionalClient) NewOptionalIntLiteralClient() *OptionalIntLiteralClient {
	return &OptionalIntLiteralClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewOptionalPlainDateClient creates a new instance of [OptionalPlainDateClient].
func (client *OptionalClient) NewOptionalPlainDateClient() *OptionalPlainDateClient {
	return &OptionalPlainDateClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewOptionalPlainTimeClient creates a new instance of [OptionalPlainTimeClient].
func (client *OptionalClient) NewOptionalPlainTimeClient() *OptionalPlainTimeClient {
	return &OptionalPlainTimeClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewOptionalRequiredAndOptionalClient creates a new instance of [OptionalRequiredAndOptionalClient].
func (client *OptionalClient) NewOptionalRequiredAndOptionalClient() *OptionalRequiredAndOptionalClient {
	return &OptionalRequiredAndOptionalClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewOptionalStringClient creates a new instance of [OptionalStringClient].
func (client *OptionalClient) NewOptionalStringClient() *OptionalStringClient {
	return &OptionalStringClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewOptionalStringLiteralClient creates a new instance of [OptionalStringLiteralClient].
func (client *OptionalClient) NewOptionalStringLiteralClient() *OptionalStringLiteralClient {
	return &OptionalStringLiteralClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewOptionalUnionFloatLiteralClient creates a new instance of [OptionalUnionFloatLiteralClient].
func (client *OptionalClient) NewOptionalUnionFloatLiteralClient() *OptionalUnionFloatLiteralClient {
	return &OptionalUnionFloatLiteralClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewOptionalUnionIntLiteralClient creates a new instance of [OptionalUnionIntLiteralClient].
func (client *OptionalClient) NewOptionalUnionIntLiteralClient() *OptionalUnionIntLiteralClient {
	return &OptionalUnionIntLiteralClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewOptionalUnionStringLiteralClient creates a new instance of [OptionalUnionStringLiteralClient].
func (client *OptionalClient) NewOptionalUnionStringLiteralClient() *OptionalUnionStringLiteralClient {
	return &OptionalUnionStringLiteralClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}
