// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package datetimegroup

import "time"

// DatetimeHeaderClientDefaultResponse contains the response from method DatetimeHeaderClient.Default.
type DatetimeHeaderClientDefaultResponse struct {
	// placeholder for future response values
}

// DatetimeHeaderClientRFC3339Response contains the response from method DatetimeHeaderClient.RFC3339.
type DatetimeHeaderClientRFC3339Response struct {
	// placeholder for future response values
}

// DatetimeHeaderClientRFC7231Response contains the response from method DatetimeHeaderClient.RFC7231.
type DatetimeHeaderClientRFC7231Response struct {
	// placeholder for future response values
}

// DatetimeHeaderClientUnixTimestampArrayResponse contains the response from method DatetimeHeaderClient.UnixTimestampArray.
type DatetimeHeaderClientUnixTimestampArrayResponse struct {
	// placeholder for future response values
}

// DatetimeHeaderClientUnixTimestampResponse contains the response from method DatetimeHeaderClient.UnixTimestamp.
type DatetimeHeaderClientUnixTimestampResponse struct {
	// placeholder for future response values
}

// DatetimePropertyClientDefaultResponse contains the response from method DatetimePropertyClient.Default.
type DatetimePropertyClientDefaultResponse struct {
	DefaultDatetimeProperty
}

// DatetimePropertyClientRFC3339Response contains the response from method DatetimePropertyClient.RFC3339.
type DatetimePropertyClientRFC3339Response struct {
	RFC3339DatetimeProperty
}

// DatetimePropertyClientRFC7231Response contains the response from method DatetimePropertyClient.RFC7231.
type DatetimePropertyClientRFC7231Response struct {
	RFC7231DatetimeProperty
}

// DatetimePropertyClientUnixTimestampArrayResponse contains the response from method DatetimePropertyClient.UnixTimestampArray.
type DatetimePropertyClientUnixTimestampArrayResponse struct {
	UnixTimestampArrayDatetimeProperty
}

// DatetimePropertyClientUnixTimestampResponse contains the response from method DatetimePropertyClient.UnixTimestamp.
type DatetimePropertyClientUnixTimestampResponse struct {
	UnixTimestampDatetimeProperty
}

// DatetimeQueryClientDefaultResponse contains the response from method DatetimeQueryClient.Default.
type DatetimeQueryClientDefaultResponse struct {
	// placeholder for future response values
}

// DatetimeQueryClientRFC3339Response contains the response from method DatetimeQueryClient.RFC3339.
type DatetimeQueryClientRFC3339Response struct {
	// placeholder for future response values
}

// DatetimeQueryClientRFC7231Response contains the response from method DatetimeQueryClient.RFC7231.
type DatetimeQueryClientRFC7231Response struct {
	// placeholder for future response values
}

// DatetimeQueryClientUnixTimestampArrayResponse contains the response from method DatetimeQueryClient.UnixTimestampArray.
type DatetimeQueryClientUnixTimestampArrayResponse struct {
	// placeholder for future response values
}

// DatetimeQueryClientUnixTimestampResponse contains the response from method DatetimeQueryClient.UnixTimestamp.
type DatetimeQueryClientUnixTimestampResponse struct {
	// placeholder for future response values
}

// DatetimeResponseHeaderClientDefaultResponse contains the response from method DatetimeResponseHeaderClient.Default.
type DatetimeResponseHeaderClientDefaultResponse struct {
	Value *time.Time
}

// DatetimeResponseHeaderClientRFC3339Response contains the response from method DatetimeResponseHeaderClient.RFC3339.
type DatetimeResponseHeaderClientRFC3339Response struct {
	Value *time.Time
}

// DatetimeResponseHeaderClientRFC7231Response contains the response from method DatetimeResponseHeaderClient.RFC7231.
type DatetimeResponseHeaderClientRFC7231Response struct {
	Value *time.Time
}

// DatetimeResponseHeaderClientUnixTimestampResponse contains the response from method DatetimeResponseHeaderClient.UnixTimestamp.
type DatetimeResponseHeaderClientUnixTimestampResponse struct {
	Value *time.Time
}
