// +build go1.13

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package complexgroup

type CMYKColors string

const (
	CMYKColorsBlacK   CMYKColors = "blacK"
	CMYKColorsCyan    CMYKColors = "cyan"
	CMYKColorsMagenta CMYKColors = "Magenta"
	CMYKColorsYellow  CMYKColors = "YELLOW"
)

func PossibleCMYKColorsValues() []CMYKColors {
	return []CMYKColors{
		CMYKColorsBlacK,
		CMYKColorsCyan,
		CMYKColorsMagenta,
		CMYKColorsYellow,
	}
}

func (c CMYKColors) ToPtr() *CMYKColors {
	return &c
}

// GoblinSharkColor - Colors possible
type GoblinSharkColor string

const (
	GoblinSharkColorBrown GoblinSharkColor = "brown"
	GoblinSharkColorGray  GoblinSharkColor = "gray"
	// GoblinSharkColorLowerRed - Lowercase RED
	GoblinSharkColorLowerRed GoblinSharkColor = "red"
	GoblinSharkColorPink     GoblinSharkColor = "pink"
	// GoblinSharkColorUpperRed - Uppercase RED
	GoblinSharkColorUpperRed GoblinSharkColor = "RED"
)

func PossibleGoblinSharkColorValues() []GoblinSharkColor {
	return []GoblinSharkColor{
		GoblinSharkColorBrown,
		GoblinSharkColorGray,
		GoblinSharkColorLowerRed,
		GoblinSharkColorPink,
		GoblinSharkColorUpperRed,
	}
}

func (c GoblinSharkColor) ToPtr() *GoblinSharkColor {
	return &c
}

type MyKind string

const (
	MyKindKind1 MyKind = "Kind1"
)

func PossibleMyKindValues() []MyKind {
	return []MyKind{
		MyKindKind1,
	}
}

func (c MyKind) ToPtr() *MyKind {
	return &c
}
