// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package fake

import (
	"context"
	"errors"
	"fmt"
	azfake "github.com/Azure/azure-sdk-for-go/sdk/azcore/fake"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/fake/server"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"naminggroup"
	"net/http"
	"net/url"
	"strings"
	"sync"
)

// NamingServer is a fake server for instances of the naminggroup.NamingClient type.
type NamingServer struct {
	// NamingHeaderServer contains the fakes for client NamingHeaderClient
	NamingHeaderServer NamingHeaderServer

	// NamingModelServer contains the fakes for client NamingModelClient
	NamingModelServer NamingModelServer

	// NamingPropertyServer contains the fakes for client NamingPropertyClient
	NamingPropertyServer NamingPropertyServer

	// NamingUnionEnumServer contains the fakes for client NamingUnionEnumClient
	NamingUnionEnumServer NamingUnionEnumServer

	// ClientName is the fake for method NamingClient.ClientName
	// HTTP status codes to indicate success: http.StatusNoContent
	ClientName func(ctx context.Context, options *naminggroup.NamingClientClientNameOptions) (resp azfake.Responder[naminggroup.NamingClientClientNameResponse], errResp azfake.ErrorResponder)

	// Parameter is the fake for method NamingClient.Parameter
	// HTTP status codes to indicate success: http.StatusNoContent
	Parameter func(ctx context.Context, clientName string, options *naminggroup.NamingClientParameterOptions) (resp azfake.Responder[naminggroup.NamingClientParameterResponse], errResp azfake.ErrorResponder)
}

// NewNamingServerTransport creates a new instance of NamingServerTransport with the provided implementation.
// The returned NamingServerTransport instance is connected to an instance of naminggroup.NamingClient via the
// azcore.ClientOptions.Transporter field in the client's constructor parameters.
func NewNamingServerTransport(srv *NamingServer) *NamingServerTransport {
	return &NamingServerTransport{srv: srv}
}

// NamingServerTransport connects instances of naminggroup.NamingClient to instances of NamingServer.
// Don't use this type directly, use NewNamingServerTransport instead.
type NamingServerTransport struct {
	srv                     *NamingServer
	trMu                    sync.Mutex
	trNamingHeaderServer    *NamingHeaderServerTransport
	trNamingModelServer     *NamingModelServerTransport
	trNamingPropertyServer  *NamingPropertyServerTransport
	trNamingUnionEnumServer *NamingUnionEnumServerTransport
}

// Do implements the policy.Transporter interface for NamingServerTransport.
func (n *NamingServerTransport) Do(req *http.Request) (*http.Response, error) {
	rawMethod := req.Context().Value(runtime.CtxAPINameKey{})
	method, ok := rawMethod.(string)
	if !ok {
		return nil, nonRetriableError{errors.New("unable to dispatch request, missing value for CtxAPINameKey")}
	}

	if client := method[:strings.Index(method, ".")]; client != "NamingClient" {
		return n.dispatchToClientFake(req, client)
	}
	return n.dispatchToMethodFake(req, method)
}

func (n *NamingServerTransport) dispatchToClientFake(req *http.Request, client string) (*http.Response, error) {
	var resp *http.Response
	var err error

	switch client {
	case "NamingHeaderClient":
		initServer(&n.trMu, &n.trNamingHeaderServer, func() *NamingHeaderServerTransport {
			return NewNamingHeaderServerTransport(&n.srv.NamingHeaderServer)
		})
		resp, err = n.trNamingHeaderServer.Do(req)
	case "NamingModelClient":
		initServer(&n.trMu, &n.trNamingModelServer, func() *NamingModelServerTransport {
			return NewNamingModelServerTransport(&n.srv.NamingModelServer)
		})
		resp, err = n.trNamingModelServer.Do(req)
	case "NamingPropertyClient":
		initServer(&n.trMu, &n.trNamingPropertyServer, func() *NamingPropertyServerTransport {
			return NewNamingPropertyServerTransport(&n.srv.NamingPropertyServer)
		})
		resp, err = n.trNamingPropertyServer.Do(req)
	case "NamingUnionEnumClient":
		initServer(&n.trMu, &n.trNamingUnionEnumServer, func() *NamingUnionEnumServerTransport {
			return NewNamingUnionEnumServerTransport(&n.srv.NamingUnionEnumServer)
		})
		resp, err = n.trNamingUnionEnumServer.Do(req)
	default:
		err = fmt.Errorf("unhandled client %s", client)
	}

	return resp, err
}

func (n *NamingServerTransport) dispatchToMethodFake(req *http.Request, method string) (*http.Response, error) {
	resultChan := make(chan result, 1)
	go func() {
		var intercepted bool
		var res result
		if namingServerTransportInterceptor != nil {
			res.resp, res.err, intercepted = namingServerTransportInterceptor.Do(req)
		}
		if !intercepted {
			switch method {
			case "NamingClient.ClientName":
				res.resp, res.err = n.dispatchClientName(req)
			case "NamingClient.Parameter":
				res.resp, res.err = n.dispatchParameter(req)
			default:
				res.err = fmt.Errorf("unhandled API %s", method)
			}

		}
		resultChan <- res
	}()

	select {
	case <-req.Context().Done():
		return nil, req.Context().Err()
	case res := <-resultChan:
		return res.resp, res.err
	}
}

func (n *NamingServerTransport) dispatchClientName(req *http.Request) (*http.Response, error) {
	if n.srv.ClientName == nil {
		return nil, &nonRetriableError{errors.New("fake for method ClientName not implemented")}
	}
	respr, errRespr := n.srv.ClientName(req.Context(), nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !contains([]int{http.StatusNoContent}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusNoContent", respContent.HTTPStatus)}
	}
	resp, err := server.NewResponse(respContent, req, nil)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (n *NamingServerTransport) dispatchParameter(req *http.Request) (*http.Response, error) {
	if n.srv.Parameter == nil {
		return nil, &nonRetriableError{errors.New("fake for method Parameter not implemented")}
	}
	qp := req.URL.Query()
	clientNameParam, err := url.QueryUnescape(qp.Get("defaultName"))
	if err != nil {
		return nil, err
	}
	respr, errRespr := n.srv.Parameter(req.Context(), clientNameParam, nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !contains([]int{http.StatusNoContent}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusNoContent", respContent.HTTPStatus)}
	}
	resp, err := server.NewResponse(respContent, req, nil)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// set this to conditionally intercept incoming requests to NamingServerTransport
var namingServerTransportInterceptor interface {
	// Do returns true if the server transport should use the returned response/error
	Do(*http.Request) (*http.Response, error, bool)
}
