version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - /packages/autorest.go/test
      - /packages/typespec-go/test
    schedule:
      interval: daily
    gropus:
      all-tests:
        patterns:
          - "*"
