// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package previewversiongroup

// PreviewVersionClientGetWidgetResponse contains the response from method PreviewVersionClient.GetWidget.
type PreviewVersionClientGetWidgetResponse struct {
	// A simple model for testing.
	Widget
}

// PreviewVersionClientListWidgetsResponse contains the response from method PreviewVersionClient.ListWidgets.
type PreviewVersionClientListWidgetsResponse struct {
	ListWidgetsResponse
}

// PreviewVersionClientUpdateWidgetColorResponse contains the response from method PreviewVersionClient.UpdateWidgetColor.
type PreviewVersionClientUpdateWidgetColorResponse struct {
	// A simple model for testing.
	Widget
}
