packages:
  - packages/autorest.go
  - packages/autorest.gotest
  - packages/codegen.go
  - packages/codemodel.go
  - packages/naming.go
  - packages/typespec-go

catalog:
  "@autorest/codemodel": ~4.19.3
  "@azure-tools/codegen": ^2.10.0
  "@azure-tools/linq": ^3.1.263
  "@eslint/js": ^9.24.0
  "@types/node": ^20.17.32
  "@vitest/coverage-v8": ^3.1.1
  "@vitest/ui": ^3.1.1
  eslint: ^9.24.0
  typescript: ^5.1.6
  typescript-eslint: ^8.30.1
  vitest: ^3.1.1
