// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package fake

import (
	"arraygroup"
	"context"
	"errors"
	"fmt"
	azfake "github.com/Azure/azure-sdk-for-go/sdk/azcore/fake"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/fake/server"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
)

// ModelValueServer is a fake server for instances of the arraygroup.ModelValueClient type.
type ModelValueServer struct {
	// Get is the fake for method ModelValueClient.Get
	// HTTP status codes to indicate success: http.StatusOK
	Get func(ctx context.Context, options *arraygroup.ModelValueClientGetOptions) (resp azfake.Responder[arraygroup.ModelValueClientGetResponse], errResp azfake.ErrorResponder)

	// Put is the fake for method ModelValueClient.Put
	// HTTP status codes to indicate success: http.StatusNoContent
	Put func(ctx context.Context, body []arraygroup.InnerModel, options *arraygroup.ModelValueClientPutOptions) (resp azfake.Responder[arraygroup.ModelValueClientPutResponse], errResp azfake.ErrorResponder)
}

// NewModelValueServerTransport creates a new instance of ModelValueServerTransport with the provided implementation.
// The returned ModelValueServerTransport instance is connected to an instance of arraygroup.ModelValueClient via the
// azcore.ClientOptions.Transporter field in the client's constructor parameters.
func NewModelValueServerTransport(srv *ModelValueServer) *ModelValueServerTransport {
	return &ModelValueServerTransport{srv: srv}
}

// ModelValueServerTransport connects instances of arraygroup.ModelValueClient to instances of ModelValueServer.
// Don't use this type directly, use NewModelValueServerTransport instead.
type ModelValueServerTransport struct {
	srv *ModelValueServer
}

// Do implements the policy.Transporter interface for ModelValueServerTransport.
func (m *ModelValueServerTransport) Do(req *http.Request) (*http.Response, error) {
	rawMethod := req.Context().Value(runtime.CtxAPINameKey{})
	method, ok := rawMethod.(string)
	if !ok {
		return nil, nonRetriableError{errors.New("unable to dispatch request, missing value for CtxAPINameKey")}
	}

	return m.dispatchToMethodFake(req, method)
}

func (m *ModelValueServerTransport) dispatchToMethodFake(req *http.Request, method string) (*http.Response, error) {
	var resp *http.Response
	var err error

	switch method {
	case "ModelValueClient.Get":
		resp, err = m.dispatchGet(req)
	case "ModelValueClient.Put":
		resp, err = m.dispatchPut(req)
	default:
		err = fmt.Errorf("unhandled API %s", method)
	}

	return resp, err
}

func (m *ModelValueServerTransport) dispatchGet(req *http.Request) (*http.Response, error) {
	if m.srv.Get == nil {
		return nil, &nonRetriableError{errors.New("fake for method Get not implemented")}
	}
	respr, errRespr := m.srv.Get(req.Context(), nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	resp, err := server.MarshalResponseAsJSON(respContent, server.GetResponse(respr).Value, req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (m *ModelValueServerTransport) dispatchPut(req *http.Request) (*http.Response, error) {
	if m.srv.Put == nil {
		return nil, &nonRetriableError{errors.New("fake for method Put not implemented")}
	}
	body, err := server.UnmarshalRequestAsJSON[[]arraygroup.InnerModel](req)
	if err != nil {
		return nil, err
	}
	respr, errRespr := m.srv.Put(req.Context(), body, nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !contains([]int{http.StatusNoContent}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusNoContent", respContent.HTTPStatus)}
	}
	resp, err := server.NewResponse(respContent, req, nil)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
