// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package datetimegroup

// HeaderClientDefaultOptions contains the optional parameters for the HeaderClient.Default method.
type HeaderClientDefaultOptions struct {
	// placeholder for future optional parameters
}

// HeaderClientRFC3339Options contains the optional parameters for the HeaderClient.RFC3339 method.
type HeaderClientRFC3339Options struct {
	// placeholder for future optional parameters
}

// HeaderClientRFC7231Options contains the optional parameters for the HeaderClient.RFC7231 method.
type HeaderClientRFC7231Options struct {
	// placeholder for future optional parameters
}

// HeaderClientUnixTimestampArrayOptions contains the optional parameters for the HeaderClient.UnixTimestampArray method.
type HeaderClientUnixTimestampArrayOptions struct {
	// placeholder for future optional parameters
}

// HeaderClientUnixTimestampOptions contains the optional parameters for the HeaderClient.UnixTimestamp method.
type HeaderClientUnixTimestampOptions struct {
	// placeholder for future optional parameters
}

// PropertyClientDefaultOptions contains the optional parameters for the PropertyClient.Default method.
type PropertyClientDefaultOptions struct {
	// placeholder for future optional parameters
}

// PropertyClientRFC3339Options contains the optional parameters for the PropertyClient.RFC3339 method.
type PropertyClientRFC3339Options struct {
	// placeholder for future optional parameters
}

// PropertyClientRFC7231Options contains the optional parameters for the PropertyClient.RFC7231 method.
type PropertyClientRFC7231Options struct {
	// placeholder for future optional parameters
}

// PropertyClientUnixTimestampArrayOptions contains the optional parameters for the PropertyClient.UnixTimestampArray method.
type PropertyClientUnixTimestampArrayOptions struct {
	// placeholder for future optional parameters
}

// PropertyClientUnixTimestampOptions contains the optional parameters for the PropertyClient.UnixTimestamp method.
type PropertyClientUnixTimestampOptions struct {
	// placeholder for future optional parameters
}

// QueryClientDefaultOptions contains the optional parameters for the QueryClient.Default method.
type QueryClientDefaultOptions struct {
	// placeholder for future optional parameters
}

// QueryClientRFC3339Options contains the optional parameters for the QueryClient.RFC3339 method.
type QueryClientRFC3339Options struct {
	// placeholder for future optional parameters
}

// QueryClientRFC7231Options contains the optional parameters for the QueryClient.RFC7231 method.
type QueryClientRFC7231Options struct {
	// placeholder for future optional parameters
}

// QueryClientUnixTimestampArrayOptions contains the optional parameters for the QueryClient.UnixTimestampArray method.
type QueryClientUnixTimestampArrayOptions struct {
	// placeholder for future optional parameters
}

// QueryClientUnixTimestampOptions contains the optional parameters for the QueryClient.UnixTimestamp method.
type QueryClientUnixTimestampOptions struct {
	// placeholder for future optional parameters
}

// ResponseHeaderClientDefaultOptions contains the optional parameters for the ResponseHeaderClient.Default method.
type ResponseHeaderClientDefaultOptions struct {
	// placeholder for future optional parameters
}

// ResponseHeaderClientRFC3339Options contains the optional parameters for the ResponseHeaderClient.RFC3339 method.
type ResponseHeaderClientRFC3339Options struct {
	// placeholder for future optional parameters
}

// ResponseHeaderClientRFC7231Options contains the optional parameters for the ResponseHeaderClient.RFC7231 method.
type ResponseHeaderClientRFC7231Options struct {
	// placeholder for future optional parameters
}

// ResponseHeaderClientUnixTimestampOptions contains the optional parameters for the ResponseHeaderClient.UnixTimestamp method.
type ResponseHeaderClientUnixTimestampOptions struct {
	// placeholder for future optional parameters
}
