// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package fake

import (
	"context"
	"errors"
	"fmt"
	azfake "github.com/Azure/azure-sdk-for-go/sdk/azcore/fake"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/fake/server"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"jsongroup"
	"net/http"
)

// JSONPropertyServer is a fake server for instances of the jsongroup.JSONPropertyClient type.
type JSONPropertyServer struct {
	// Get is the fake for method JSONPropertyClient.Get
	// HTTP status codes to indicate success: http.StatusOK
	Get func(ctx context.Context, options *jsongroup.JSONPropertyClientGetOptions) (resp azfake.Responder[jsongroup.JSONPropertyClientGetResponse], errResp azfake.ErrorResponder)

	// Send is the fake for method JSONPropertyClient.Send
	// HTTP status codes to indicate success: http.StatusNoContent
	Send func(ctx context.Context, body jsongroup.JSONEncodedNameModel, options *jsongroup.JSONPropertyClientSendOptions) (resp azfake.Responder[jsongroup.JSONPropertyClientSendResponse], errResp azfake.ErrorResponder)
}

// NewJSONPropertyServerTransport creates a new instance of JSONPropertyServerTransport with the provided implementation.
// The returned JSONPropertyServerTransport instance is connected to an instance of jsongroup.JSONPropertyClient via the
// azcore.ClientOptions.Transporter field in the client's constructor parameters.
func NewJSONPropertyServerTransport(srv *JSONPropertyServer) *JSONPropertyServerTransport {
	return &JSONPropertyServerTransport{srv: srv}
}

// JSONPropertyServerTransport connects instances of jsongroup.JSONPropertyClient to instances of JSONPropertyServer.
// Don't use this type directly, use NewJSONPropertyServerTransport instead.
type JSONPropertyServerTransport struct {
	srv *JSONPropertyServer
}

// Do implements the policy.Transporter interface for JSONPropertyServerTransport.
func (j *JSONPropertyServerTransport) Do(req *http.Request) (*http.Response, error) {
	rawMethod := req.Context().Value(runtime.CtxAPINameKey{})
	method, ok := rawMethod.(string)
	if !ok {
		return nil, nonRetriableError{errors.New("unable to dispatch request, missing value for CtxAPINameKey")}
	}

	return j.dispatchToMethodFake(req, method)
}

func (j *JSONPropertyServerTransport) dispatchToMethodFake(req *http.Request, method string) (*http.Response, error) {
	var resp *http.Response
	var err error

	switch method {
	case "JSONPropertyClient.Get":
		resp, err = j.dispatchGet(req)
	case "JSONPropertyClient.Send":
		resp, err = j.dispatchSend(req)
	default:
		err = fmt.Errorf("unhandled API %s", method)
	}

	return resp, err
}

func (j *JSONPropertyServerTransport) dispatchGet(req *http.Request) (*http.Response, error) {
	if j.srv.Get == nil {
		return nil, &nonRetriableError{errors.New("fake for method Get not implemented")}
	}
	respr, errRespr := j.srv.Get(req.Context(), nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	resp, err := server.MarshalResponseAsJSON(respContent, server.GetResponse(respr).JSONEncodedNameModel, req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (j *JSONPropertyServerTransport) dispatchSend(req *http.Request) (*http.Response, error) {
	if j.srv.Send == nil {
		return nil, &nonRetriableError{errors.New("fake for method Send not implemented")}
	}
	body, err := server.UnmarshalRequestAsJSON[jsongroup.JSONEncodedNameModel](req)
	if err != nil {
		return nil, err
	}
	respr, errRespr := j.srv.Send(req.Context(), body, nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !contains([]int{http.StatusNoContent}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusNoContent", respContent.HTTPStatus)}
	}
	resp, err := server.NewResponse(respContent, req, nil)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
