// +build go1.13

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package headgroup

import "net/http"

// BooleanResponse contains a boolean response.
type BooleanResponse struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response

	// Success indicates if the operation succeeded or failed.
	Success bool
}

// HTTPSuccessHead200Options contains the optional parameters for the HTTPSuccess.Head200 method.
type HTTPSuccessHead200Options struct {
	// placeholder for future optional parameters
}

// HTTPSuccessHead204Options contains the optional parameters for the HTTPSuccess.Head204 method.
type HTTPSuccessHead204Options struct {
	// placeholder for future optional parameters
}

// HTTPSuccessHead404Options contains the optional parameters for the HTTPSuccess.Head404 method.
type HTTPSuccessHead404Options struct {
	// placeholder for future optional parameters
}
