schedules:
- cron: '0 0 * * *'
  displayName: Daily midnight build
  branches:
    include:
    - main
  always: true

trigger: none
pr: none

jobs:
- job: Go_Nightly_Build
  timeoutInMinutes: 120
  variables:
    - template: /eng/pipelines/templates/variables/image.yml
  pool:
    name: "$(LINUXNEXTPOOL)"
    image: "$(LINUXNEXTVMIMAGE)"
    os: linux
  steps:
    - template: /eng/pipelines/templates/steps/set-env.yaml
    - script: |
          npm install -g @typespec/compiler@next
          npx @azure-tools/typespec-bump-deps packages/typespec-go/package.json --add-npm-overrides
          echo "typespec-go/package.json"
          cat packages/typespec-go/package.json
      displayName: 'Bump TypeSpec Dependencies to dev'
    - template: /eng/pipelines/templates/steps/build-test-typespec.yaml
      parameters:
        Nightly: true
