trigger:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    exclude:
      - packages/autorest.go
      - packages/autorest.gotest
      - swagger

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    exclude:
      - packages/autorest.go
      - packages/autorest.gotest
      - swagger

jobs:
  - job: "TypeSpec_Go_CI"
    displayName: "Run TypeSpec Go CI Checks"

    strategy:
      matrix:
        Linux:
          image: $(LINUXNEXTVMIMAGE)
          pool: $(LINUXPOOL)
    pool:
      name: $(pool)
      image: "$(image)"
      os: linux

    steps:
      - template: ../steps/set-env.yaml

      - template: ../steps/build-test-typespec.yaml
