trigger:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    exclude:
      - packages/autorest.go
      - packages/autorest.gotest
      - swagger

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    exclude:
      - packages/autorest.go
      - packages/autorest.gotest
      - swagger

extends:
  template: /eng/pipelines/templates/stages/1es-redirect.yml
  parameters:
    Use1ESOfficial: false
    stages:
      - stage: "TypeSpec_Go_CI"
        jobs:
          - job: "TypeSpec_Go_CI"
            displayName: "Run TypeSpec Go CI Checks - go1.21"

            variables:
              - template: /eng/pipelines/templates/variables/image.yml

            pool:
              name: "$(LINUXNEXTPOOL)"
              image: "$(LINUXNEXTVMIMAGE)"
              os: linux

            steps:
              - template: /eng/pipelines/templates/steps/set-env.yaml
                parameters:
                  GoVersion: "1.21.4"

              - template: /eng/pipelines/templates/steps/build-test-typespec.yaml
