trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

variables:
  NodeVersion: '10.15.3'
  GOPATH: '$(system.defaultWorkingDirectory)/work'
  sdkPath: '$(GOPATH)/src/github.com/$(build.repository.name)'

jobs:
  - job: 'AutoRest_Go_CI'
    displayName: 'Run AutoRest CI Checks'

    strategy:
      matrix:
        Linux_Go113:
          vm.image: 'ubuntu-18.04'
          go.version: '1.13'
          GOROOT: '/usr/local/go$(go.version)'
        Linux_Go114:
          vm.image: 'ubuntu-18.04'
          go.version: '1.14'
          GOROOT: '/usr/local/go$(go.version)'

    pool:
      vmImage: '$(vm.image)'

    steps:
      - task: NodeTool@0
        displayName: 'Install Node $(NodeVersion)'
        inputs:
          versionSpec: '$(NodeVersion)'

      - script: |
          set -e
          mkdir -p '$(GOPATH)/bin'
          mkdir -p '$(sdkPath)'
          shopt -s extglob
          mv !(work) '$(sdkPath)'
          echo '##vso[task.prependpath]$(GOROOT)/bin'
          echo '##vso[task.prependpath]$(GOPATH)/bin'
        displayName: 'Create Go Workspace'

      - script: |
          sudo apt-get install libunwind8
          npm install
          npm install -g gulp-cli
        displayName: 'Prepare Generator Environment'

      - script: |
          gulp testci
        displayName: 'Gulp testci'
