trigger:
  branches:
    include:
    - track2

pr:
  branches:
    include:
    - track2

variables:
  NodeVersion: '10.x'
  goTestPath: '$(system.defaultWorkingDirectory)/test'

jobs:
  - job: 'AutoRest_Go_CI'
    displayName: 'Run AutoRest CI Checks'

    strategy:
      matrix:
        Linux_Go113:
          vm.image: 'ubuntu-18.04'
          go.version: '1.13'
          GOROOT: '/usr/local/go$(go.version)'

    pool:
      vmImage: '$(vm.image)'

    steps:
      - task: NodeTool@0
        displayName: 'Install Node $(NodeVersion)'
        inputs:
          versionSpec: '$(NodeVersion)'

      - script: |
          cd $(Build.SourcesDirectory)
          npm install -g "@microsoft/rush"
          rush update
          rush install
          npm install -g "@autorest/autorest"
        displayName: 'Prepare Generator Environment'

      - script: |
          rush build
        displayName: 'Build Generator Sources'

      - script: |
          set -e
          echo '##vso[task.prependpath]$(GOROOT)/bin'
        displayName: 'Create Go Workspace'

      - script: |
          set -e
          go version
        displayName: 'Install Dependencies'

      - script: go vet $(go list ./...)
        displayName: 'Vet'
        workingDirectory: '$(goTestPath)'

      - script: |
          pushd ../src/node_modules/@autorest/test-server
          npm start
          popd
          go test ./...
          pushd ../src/node_modules/@autorest/test-server
          npm stop
        displayName: 'Run Acceptance Tests'
        workingDirectory: '$(goTestPath)'
