schedules:
- cron: '0 0 * * *'
  displayName: Nightly dev build
  branches:
    include:
    - main

trigger: none
pr: none

parameters:
- name: UseTypeSpecNext
  displayName: Use TypeSpec "next" version
  type: boolean
  default: true

resources:
  repositories:
    - repository: sdk-repository
      type: github
      endpoint: Azure
      name: Azure/azure-sdk-for-go
      ref: refs/heads/users/pahallis/cookiecutter
    - repository: azure-sdk-tools
      type: github
      endpoint: Azure
      name: Azure/azure-sdk-tools
      ref: refs/heads/main

pool:
  name: azsdk-pool-mms-win-2022-general
  vmImage: windows-2022

extends:
  template: eng/pipelines/templates/stages/archetype-autorest-preview.yml@azure-sdk-tools
  parameters:
    RegenerationJobCount: 3
    BuildAlphaVersion: true
    UseTypeSpecNext: ${{ parameters.UseTypeSpecNext }}
    Packages:
    - name: generator
      file: autorest-go-*.tgz
      type: npm
    PublishTarget: 'internal'
    SdkInitializationSteps:
    - pwsh: |
        $packageVersions = Get-Content "$(buildArtifactsPath)/package-versions.json" -Raw | ConvertFrom-Json
        $generatorVersion = $packageVersions.generator

        $pattern = '(?m)^use: "@autorest/go(@.*)"\s*$'
        $mdFiles = Get-ChildItem -Path "./sdk" -Filter "autorest.md" -Recurse
        foreach ($mdFile in $mdFiles) {
          $content = Get-Content -Path $mdFile -Raw

          if ($content -match $pattern) {
            Write-Host "Update @autorest/go version in $mdFile"
            $content = $content -replace $pattern, "use: `"@autorest/go@$generatorVersion`""
            Set-Content -Path $mdFile -Value $content -Encoding UTF8 -NoNewLine
          }
        }
      displayName: 'Update autorest.md files'
      workingDirectory: $(sdkRepositoryPath)
