schedules:
- cron: '0 0 * * *'
  displayName: Nightly dev build
  branches:
    include:
    - main

trigger: none
pr: none

parameters:
- name: UseTypeSpecNext
  displayName: Use TypeSpec "next" version
  type: boolean
  default: true

resources:
  repositories:
    - repository: sdk-repository
      type: github
      endpoint: Azure
      name: Azure/azure-sdk-for-go
      ref: refs/heads/users/pahallis/cookiecutter
    - repository: azure-sdk-tools
      type: github
      endpoint: Azure
      name: Azure/azure-sdk-tools
      ref: refs/heads/main

pool:
  name: azsdk-pool-mms-win-2022-general
  vmImage: windows-2022

extends:
  template: eng/pipelines/templates/stages/archetype-autorest-preview.yml@azure-sdk-tools
  parameters:
    RegenerationJobCount: 3
    BuildAlphaVersion: true
    UseTypeSpecNext: ${{ parameters.UseTypeSpecNext }}
    Packages:
    - name: generator
      file: autorest-go-*.tgz
      type: npm
    PublishTarget: 'internal'
    SdkInitializationSteps:
    - pwsh: |
        $packageVersions = Get-Content "$(buildArtifactsPath)/package-versions.json" -Raw | ConvertFrom-Json
        $generatorVersion = $packageVersions.generator

        $files = @(
          'eng/scripts/build.ps1'
          'eng/scripts/MgmtTestLib.ps1'
        )

        foreach ($file in $files) {
          $content = Get-Content -Path $file -Raw

          if ($content -match '"@autorest/go@.*?"') {
            $content = $content -replace $Matches[0], "`"@autorest/go@$generatorVersion`""

            Write-Host "Update @autorest/go version in $file"
            Set-Content -Path $file -Value $content -Encoding UTF8 -NoNewLine
          }
        }
      displayName: 'Update autorest.md files'
      workingDirectory: $(sdkRepositoryPath)
