trigger: none
pr: none

pool:
  vmImage: "ubuntu-18.04"

steps:
  - template: ../steps/set-env.yaml
    parameters:
      NodeVersion: "16.x"
      GoVersion: "1.18"

  - template: ../steps/build-test.yaml

  - pwsh: |
      $currentVersion = node -p -e "require('./src/package.json').version";
      cd src
      npm version --no-git-tag-version $currentVersion
      npm pack;
      npx publish-release --token $(azuresdk-github-pat) --repo autorest.go --owner azure --name "Autorest for Go v$currentVersion" --tag v$currentVersion --notes='Autorest for Go track 2' --prerelease --editRelease false --assets autorest-go-$currentVersion.tgz --target_commitish $(Build.SourceBranchName);
    displayName: "Publish GitHub Release"

  - script: |
      cd src
      echo "//registry.npmjs.org/:_authToken=$(azure-sdk-npm-token)" > ./.npmrc
      npm publish --access public
    displayName: "Publish to npm"
