trigger: none
pr: none

parameters:
- name: publish_dev
  displayName: 'Publish Dev Release only'
  type: boolean
  default: true
- name: release_autorestgo
  displayName: '@autorest/go'
  type: boolean
  default: false
- name: release_autorestgotest
  displayName: '@autorest/gotest'
  type: boolean
  default: false
- name: release_typespecgo
  displayName: '@azure-tools/typespec-go'
  type: boolean
  default: false

variables:
  BuildNpmrcPath: "$(Agent.TempDirectory)/publish-release/.npmrc"

extends: 
  template: /eng/pipelines/templates/stages/1es-redirect.yml
  parameters:
    stages:
    - stage: Build

      variables:
        - template: /eng/pipelines/templates/variables/globals.yml

      jobs:
        - job: Build
          pool:
            image: ubuntu-24.04
            name: azsdk-pool
            os: linux
          templateContext:
            outputs:
              - output: pipelineArtifact
                displayName: "Publish release tarballs"
                targetPath: "$(Build.ArtifactStagingDirectory)/release-assets"
                artifactName: "release_assets"
          steps:
            - checkout: self
              path: s

            - template: /eng/pipelines/templates/steps/set-env.yaml
              parameters:
                GoVersion: $(GoVersionLatest)
                npmrcPath: $(BuildNpmrcPath)

            - pwsh: |
                New-Item -ItemType Directory -Force -Path "$(Build.ArtifactStagingDirectory)/release-assets" | Out-Null
              displayName: "Create release artifacts directory"

            - ${{ if eq(parameters.release_autorestgo, true) }}:
              - template: /eng/pipelines/templates/steps/build-test-go.yaml
                parameters:
                  npmrcPath: $(BuildNpmrcPath)
              - template: /eng/pipelines/templates/steps/publish-release.yaml
                parameters:
                  PackagePath: "autorest.go"
                  PackageFileName: "autorest-go"
                  ReleaseName: "Autorest for Go v$(currentVersion)"
                  ReleaseNotes: "Autorest for Go track 2"
                  PublishDevVersion: ${{ parameters.publish_dev }}
                  Operation: "pack"
                  InputType: "source"
                  npmrcPath: $(BuildNpmrcPath)

            - ${{ if eq(parameters.release_autorestgotest, true) }}:
              - template: /eng/pipelines/templates/steps/build-test-gotest.yaml
                parameters:
                  npmrcPath: $(BuildNpmrcPath)
              - template: /eng/pipelines/templates/steps/publish-release.yaml
                parameters:
                  PackagePath: "autorest.gotest"
                  PackageFileName: "autorest-gotest"
                  ReleaseName: "@autorest/gotest_v$(currentVersion)"
                  ReleaseNotes: "Go test generation"
                  PublishDevVersion: ${{ parameters.publish_dev }}
                  Operation: "pack"
                  InputType: "source"
                  npmrcPath: $(BuildNpmrcPath)

            - ${{ if eq(parameters.release_typespecgo, true) }}:
              - template: /eng/pipelines/templates/steps/build-test-typespec.yaml
                parameters:
                  npmrcPath: $(BuildNpmrcPath)
              - template: /eng/pipelines/templates/steps/publish-release.yaml
                parameters:
                  PackagePath: "typespec-go"
                  PackageFileName: "azure-tools-typespec-go"
                  ReleaseName: "TypeSpec emitter for Go SDKs v$(currentVersion)"
                  ReleaseNotes: "TypeSpec emitter for Go SDKs"
                  PublishDevVersion: ${{ parameters.publish_dev }}
                  Operation: "pack"
                  InputType: "source"
                  npmrcPath: $(BuildNpmrcPath)

    - stage: Release
      dependsOn: Build

      variables:
        - template: /eng/pipelines/templates/variables/globals.yml

      jobs:
        - deployment: Release
          pool:
            image: ubuntu-24.04
            name: azsdk-pool
            os: linux
          environment: package-publish
          templateContext:
            type: releaseJob
            isProduction: true
            inputs:
              - input: pipelineArtifact
                artifactName: release_assets
                targetPath: $(Pipeline.Workspace)/release-assets

          strategy:
            runOnce:
              deploy:
                steps:
                  - task: NodeTool@0
                    displayName: "Install Node.js $(NodeVersion)"
                    inputs:
                      versionSpec: "$(NodeVersion)"

                  - ${{ if ne(parameters.publish_dev, true) }}:
                    - pwsh: |
                        "//registry.npmjs.org/:_authToken=$(azure-sdk-npm-token)" | Out-File -FilePath "$HOME/.npmrc" -Encoding ascii
                      displayName: "Configure npm auth"

                  - ${{ if eq(parameters.release_autorestgo, true) }}:
                    - template: /eng/pipelines/templates/steps/publish-release.yaml
                      parameters:
                        PackagePath: "autorest.go"
                        PackageFileName: "autorest-go"
                        ReleaseName: "Autorest for Go v$(currentVersion)"
                        ReleaseNotes: "Autorest for Go track 2"
                        PublishDevVersion: ${{ parameters.publish_dev }}
                        Operation: "publish"
                        InputType: "artifact"

                  - ${{ if eq(parameters.release_autorestgotest, true) }}:
                    - template: /eng/pipelines/templates/steps/publish-release.yaml
                      parameters:
                        PackagePath: "autorest.gotest"
                        PackageFileName: "autorest-gotest"
                        ReleaseName: "@autorest/gotest_v$(currentVersion)"
                        ReleaseNotes: "Go test generation"
                        PublishDevVersion: ${{ parameters.publish_dev }}
                        Operation: "publish"
                        InputType: "artifact"

                  - ${{ if eq(parameters.release_typespecgo, true) }}:
                    - template: /eng/pipelines/templates/steps/publish-release.yaml
                      parameters:
                        PackagePath: "typespec-go"
                        PackageFileName: "azure-tools-typespec-go"
                        ReleaseName: "TypeSpec emitter for Go SDKs v$(currentVersion)"
                        ReleaseNotes: "TypeSpec emitter for Go SDKs"
                        PublishDevVersion: ${{ parameters.publish_dev }}
                        Operation: "publish"
                        InputType: "artifact"
