trigger: none
pr: none

pool:
  vmImage: "ubuntu-22.04"

steps:
  - template: ../steps/set-env.yaml
    parameters:
      NodeVersion: "18.x"
      GoVersion: "1.21.4"

  - template: ../steps/build-test-go.yaml

  - pwsh: |
      $currentVersion = node -p -e "require('./packages/autorest.go/package.json').version";
      $currentVersion="$currentVersion-$(Build.BuildNumber)";
      cd packages/autorest.go
      npm version --no-git-tag-version $currentVersion
      npm pack;
      npx publish-release --token $(package-write-token) --repo autorest.go --owner azure --name "Autorest for Go v$currentVersion" --tag v$currentVersion --notes='Preview version of Autorest for Go track 2' --prerelease --editRelease false --assets autorest-go-$currentVersion.tgz --target_commitish $(Build.SourceBranchName);
    displayName: "Publish Dev Release"
