trigger: none
pr: none

pool:
  vmImage: "ubuntu-22.04"

steps:
  - template: ../steps/set-env.yaml

  - template: ../steps/build-test-typespec.yaml

  - pwsh: |
      $currentVersion = node -p -e "require('$(System.DefaultWorkingDirectory)/packages/typespec-go/package.json').version";
      $currentVersion="$currentVersion-$(Build.BuildNumber)";
      cd packages/typespec-go
      npm version --no-git-tag-version $currentVersion
      npm pack;
      npm install -g azure-tools-typespec-go-$currentVersion.tgz
      if ($LASTEXITCODE) {
        exit $LASTEXITCODE
      }
      npx publish-release --token $(package-write-token) --repo autorest.go --owner azure --name "TypeSpec emitter for Go v$currentVersion" --tag v$currentVersion --notes='Beta version of TypeSpec emitter for Go SDKs' --prerelease --editRelease false --assets azure-tools-typespec-go-$currentVersion.tgz --target_commitish $(Build.SourceBranchName);
    displayName: "Publish Dev Release"
