// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package fake

import (
	"context"
	"errors"
	"fmt"
	azfake "github.com/Azure/azure-sdk-for-go/sdk/azcore/fake"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/fake/server"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
	"net/url"
	"overridegroup"
)

// OverrideGroupParametersServer is a fake server for instances of the overridegroup.OverrideGroupParametersClient type.
type OverrideGroupParametersServer struct {
	// Group is the fake for method OverrideGroupParametersClient.Group
	// HTTP status codes to indicate success: http.StatusNoContent
	Group func(ctx context.Context, options overridegroup.GroupParametersOptions, opts *overridegroup.OverrideGroupParametersClientGroupOptions) (resp azfake.Responder[overridegroup.OverrideGroupParametersClientGroupResponse], errResp azfake.ErrorResponder)
}

// NewOverrideGroupParametersServerTransport creates a new instance of OverrideGroupParametersServerTransport with the provided implementation.
// The returned OverrideGroupParametersServerTransport instance is connected to an instance of overridegroup.OverrideGroupParametersClient via the
// azcore.ClientOptions.Transporter field in the client's constructor parameters.
func NewOverrideGroupParametersServerTransport(srv *OverrideGroupParametersServer) *OverrideGroupParametersServerTransport {
	return &OverrideGroupParametersServerTransport{srv: srv}
}

// OverrideGroupParametersServerTransport connects instances of overridegroup.OverrideGroupParametersClient to instances of OverrideGroupParametersServer.
// Don't use this type directly, use NewOverrideGroupParametersServerTransport instead.
type OverrideGroupParametersServerTransport struct {
	srv *OverrideGroupParametersServer
}

// Do implements the policy.Transporter interface for OverrideGroupParametersServerTransport.
func (o *OverrideGroupParametersServerTransport) Do(req *http.Request) (*http.Response, error) {
	rawMethod := req.Context().Value(runtime.CtxAPINameKey{})
	method, ok := rawMethod.(string)
	if !ok {
		return nil, nonRetriableError{errors.New("unable to dispatch request, missing value for CtxAPINameKey")}
	}

	return o.dispatchToMethodFake(req, method)
}

func (o *OverrideGroupParametersServerTransport) dispatchToMethodFake(req *http.Request, method string) (*http.Response, error) {
	resultChan := make(chan result)
	defer close(resultChan)

	go func() {
		var intercepted bool
		var res result
		if overrideGroupParametersServerTransportInterceptor != nil {
			res.resp, res.err, intercepted = overrideGroupParametersServerTransportInterceptor.Do(req)
		}
		if !intercepted {
			switch method {
			case "OverrideGroupParametersClient.Group":
				res.resp, res.err = o.dispatchGroup(req)
			default:
				res.err = fmt.Errorf("unhandled API %s", method)
			}

		}
		select {
		case resultChan <- res:
		case <-req.Context().Done():
		}
	}()

	select {
	case <-req.Context().Done():
		return nil, req.Context().Err()
	case res := <-resultChan:
		return res.resp, res.err
	}
}

func (o *OverrideGroupParametersServerTransport) dispatchGroup(req *http.Request) (*http.Response, error) {
	if o.srv.Group == nil {
		return nil, &nonRetriableError{errors.New("fake for method Group not implemented")}
	}
	qp := req.URL.Query()
	param1Param, err := url.QueryUnescape(qp.Get("param1"))
	if err != nil {
		return nil, err
	}
	param2Param, err := url.QueryUnescape(qp.Get("param2"))
	if err != nil {
		return nil, err
	}
	options := overridegroup.GroupParametersOptions{
		Param1: param1Param,
		Param2: param2Param,
	}
	respr, errRespr := o.srv.Group(req.Context(), options, nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !contains([]int{http.StatusNoContent}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusNoContent", respContent.HTTPStatus)}
	}
	resp, err := server.NewResponse(respContent, req, nil)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// set this to conditionally intercept incoming requests to OverrideGroupParametersServerTransport
var overrideGroupParametersServerTransportInterceptor interface {
	// Do returns true if the server transport should use the returned response/error
	Do(*http.Request) (*http.Response, error, bool)
}
