// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package fake

import (
	"apiversionpathgroup"
	"context"
	"errors"
	"fmt"
	azfake "github.com/Azure/azure-sdk-for-go/sdk/azcore/fake"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/fake/server"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
)

// PathServer is a fake server for instances of the apiversionpathgroup.PathClient type.
type PathServer struct {
	// PathAPIVersion is the fake for method PathClient.PathAPIVersion
	// HTTP status codes to indicate success: http.StatusOK
	PathAPIVersion func(ctx context.Context, options *apiversionpathgroup.PathClientPathAPIVersionOptions) (resp azfake.Responder[apiversionpathgroup.PathClientPathAPIVersionResponse], errResp azfake.ErrorResponder)
}

// NewPathServerTransport creates a new instance of PathServerTransport with the provided implementation.
// The returned PathServerTransport instance is connected to an instance of apiversionpathgroup.PathClient via the
// azcore.ClientOptions.Transporter field in the client's constructor parameters.
func NewPathServerTransport(srv *PathServer) *PathServerTransport {
	return &PathServerTransport{srv: srv}
}

// PathServerTransport connects instances of apiversionpathgroup.PathClient to instances of PathServer.
// Don't use this type directly, use NewPathServerTransport instead.
type PathServerTransport struct {
	srv *PathServer
}

// Do implements the policy.Transporter interface for PathServerTransport.
func (p *PathServerTransport) Do(req *http.Request) (*http.Response, error) {
	rawMethod := req.Context().Value(runtime.CtxAPINameKey{})
	method, ok := rawMethod.(string)
	if !ok {
		return nil, nonRetriableError{errors.New("unable to dispatch request, missing value for CtxAPINameKey")}
	}

	return p.dispatchToMethodFake(req, method)
}

func (p *PathServerTransport) dispatchToMethodFake(req *http.Request, method string) (*http.Response, error) {
	resultChan := make(chan result)
	defer close(resultChan)

	go func() {
		var intercepted bool
		var res result
		if pathServerTransportInterceptor != nil {
			res.resp, res.err, intercepted = pathServerTransportInterceptor.Do(req)
		}
		if !intercepted {
			switch method {
			case "PathClient.PathAPIVersion":
				res.resp, res.err = p.dispatchPathAPIVersion(req)
			default:
				res.err = fmt.Errorf("unhandled API %s", method)
			}

		}
		select {
		case resultChan <- res:
		case <-req.Context().Done():
		}
	}()

	select {
	case <-req.Context().Done():
		return nil, req.Context().Err()
	case res := <-resultChan:
		return res.resp, res.err
	}
}

func (p *PathServerTransport) dispatchPathAPIVersion(req *http.Request) (*http.Response, error) {
	if p.srv.PathAPIVersion == nil {
		return nil, &nonRetriableError{errors.New("fake for method PathAPIVersion not implemented")}
	}
	respr, errRespr := p.srv.PathAPIVersion(req.Context(), nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	resp, err := server.NewResponse(respContent, req, nil)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// set this to conditionally intercept incoming requests to PathServerTransport
var pathServerTransportInterceptor interface {
	// Do returns true if the server transport should use the returned response/error
	Do(*http.Request) (*http.Response, error, bool)
}
