// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package fake

import (
	"addlpropsgroup"
	"context"
	"errors"
	"fmt"
	azfake "github.com/Azure/azure-sdk-for-go/sdk/azcore/fake"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/fake/server"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
)

// ExtendsUnknownServer is a fake server for instances of the addlpropsgroup.ExtendsUnknownClient type.
type ExtendsUnknownServer struct {
	// Get is the fake for method ExtendsUnknownClient.Get
	// HTTP status codes to indicate success: http.StatusOK
	Get func(ctx context.Context, options *addlpropsgroup.ExtendsUnknownClientGetOptions) (resp azfake.Responder[addlpropsgroup.ExtendsUnknownClientGetResponse], errResp azfake.ErrorResponder)

	// Put is the fake for method ExtendsUnknownClient.Put
	// HTTP status codes to indicate success: http.StatusNoContent
	Put func(ctx context.Context, body addlpropsgroup.ExtendsUnknownAdditionalProperties, options *addlpropsgroup.ExtendsUnknownClientPutOptions) (resp azfake.Responder[addlpropsgroup.ExtendsUnknownClientPutResponse], errResp azfake.ErrorResponder)
}

// NewExtendsUnknownServerTransport creates a new instance of ExtendsUnknownServerTransport with the provided implementation.
// The returned ExtendsUnknownServerTransport instance is connected to an instance of addlpropsgroup.ExtendsUnknownClient via the
// azcore.ClientOptions.Transporter field in the client's constructor parameters.
func NewExtendsUnknownServerTransport(srv *ExtendsUnknownServer) *ExtendsUnknownServerTransport {
	return &ExtendsUnknownServerTransport{srv: srv}
}

// ExtendsUnknownServerTransport connects instances of addlpropsgroup.ExtendsUnknownClient to instances of ExtendsUnknownServer.
// Don't use this type directly, use NewExtendsUnknownServerTransport instead.
type ExtendsUnknownServerTransport struct {
	srv *ExtendsUnknownServer
}

// Do implements the policy.Transporter interface for ExtendsUnknownServerTransport.
func (e *ExtendsUnknownServerTransport) Do(req *http.Request) (*http.Response, error) {
	rawMethod := req.Context().Value(runtime.CtxAPINameKey{})
	method, ok := rawMethod.(string)
	if !ok {
		return nil, nonRetriableError{errors.New("unable to dispatch request, missing value for CtxAPINameKey")}
	}

	var resp *http.Response
	var err error

	switch method {
	case "ExtendsUnknownClient.Get":
		resp, err = e.dispatchGet(req)
	case "ExtendsUnknownClient.Put":
		resp, err = e.dispatchPut(req)
	default:
		err = fmt.Errorf("unhandled API %s", method)
	}

	if err != nil {
		return nil, err
	}

	return resp, nil
}

func (e *ExtendsUnknownServerTransport) dispatchGet(req *http.Request) (*http.Response, error) {
	if e.srv.Get == nil {
		return nil, &nonRetriableError{errors.New("fake for method Get not implemented")}
	}
	respr, errRespr := e.srv.Get(req.Context(), nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	resp, err := server.MarshalResponseAsJSON(respContent, server.GetResponse(respr).ExtendsUnknownAdditionalProperties, req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (e *ExtendsUnknownServerTransport) dispatchPut(req *http.Request) (*http.Response, error) {
	if e.srv.Put == nil {
		return nil, &nonRetriableError{errors.New("fake for method Put not implemented")}
	}
	body, err := server.UnmarshalRequestAsJSON[addlpropsgroup.ExtendsUnknownAdditionalProperties](req)
	if err != nil {
		return nil, err
	}
	respr, errRespr := e.srv.Put(req.Context(), body, nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !contains([]int{http.StatusNoContent}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusNoContent", respContent.HTTPStatus)}
	}
	resp, err := server.NewResponse(respContent, req, nil)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
