// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package versionedgroup

// VersionedClientWithPathAPIVersionResponse contains the response from method VersionedClient.WithPathAPIVersion.
type VersionedClientWithPathAPIVersionResponse struct {
	// Success indicates if the operation succeeded or failed.
	Success bool
}

// VersionedClientWithQueryAPIVersionResponse contains the response from method VersionedClient.WithQueryAPIVersion.
type VersionedClientWithQueryAPIVersionResponse struct {
	// Success indicates if the operation succeeded or failed.
	Success bool
}

// VersionedClientWithoutAPIVersionResponse contains the response from method VersionedClient.WithoutAPIVersion.
type VersionedClientWithoutAPIVersionResponse struct {
	// Success indicates if the operation succeeded or failed.
	Success bool
}
