// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package commonpropsgroup

// ErrorClientCreateForUserDefinedErrorOptions contains the optional parameters for the ErrorClient.CreateForUserDefinedError
// method.
type ErrorClientCreateForUserDefinedErrorOptions struct {
	// placeholder for future optional parameters
}

// ErrorClientGetForPredefinedErrorOptions contains the optional parameters for the ErrorClient.GetForPredefinedError method.
type ErrorClientGetForPredefinedErrorOptions struct {
	// placeholder for future optional parameters
}

// ManagedIdentityClientCreateWithSystemAssignedOptions contains the optional parameters for the ManagedIdentityClient.CreateWithSystemAssigned
// method.
type ManagedIdentityClientCreateWithSystemAssignedOptions struct {
	// placeholder for future optional parameters
}

// ManagedIdentityClientGetOptions contains the optional parameters for the ManagedIdentityClient.Get method.
type ManagedIdentityClientGetOptions struct {
	// placeholder for future optional parameters
}

// ManagedIdentityClientUpdateWithUserAssignedAndSystemAssignedOptions contains the optional parameters for the ManagedIdentityClient.UpdateWithUserAssignedAndSystemAssigned
// method.
type ManagedIdentityClientUpdateWithUserAssignedAndSystemAssignedOptions struct {
	// placeholder for future optional parameters
}
