// +build go1.13

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package reportgroup

import "net/http"

// AutoRestReportServiceGetOptionalReportOptions contains the optional parameters for the AutoRestReportService.GetOptionalReport method.
type AutoRestReportServiceGetOptionalReportOptions struct {
	// If specified, qualifies the generated report further (e.g. '2.7' vs '3.5' in for Python). The only effect is, that generators that run all tests several
	// times, can distinguish the generated reports.
	Qualifier *string
}

// AutoRestReportServiceGetReportOptions contains the optional parameters for the AutoRestReportService.GetReport method.
type AutoRestReportServiceGetReportOptions struct {
	// If specified, qualifies the generated report further (e.g. '2.7' vs '3.5' in for Python). The only effect is, that generators that run all tests several
	// times, can distinguish the generated reports.
	Qualifier *string
}

// Implements the error and azcore.HTTPResponse interfaces.
type Error struct {
	raw     string
	Message *string `json:"message,omitempty"`
	Status  *int32  `json:"status,omitempty"`
}

// Error implements the error interface for type Error.
// The contents of the error text are not contractual and subject to change.
func (e Error) Error() string {
	return e.raw
}

// MapOfInt32Response is the response envelope for operations that return a map[string]*int32 type.
type MapOfInt32Response struct {
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response

	// Dictionary of <integer>
	Value map[string]*int32
}
