//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package twoopgroup

// Group1ClientFourResponse contains the response from method Group1Client.Four.
type Group1ClientFourResponse struct {
	// placeholder for future response values
}

// Group1ClientOneResponse contains the response from method Group1Client.One.
type Group1ClientOneResponse struct {
	// placeholder for future response values
}

// Group1ClientThreeResponse contains the response from method Group1Client.Three.
type Group1ClientThreeResponse struct {
	// placeholder for future response values
}

// Group2ClientFiveResponse contains the response from method Group2Client.Five.
type Group2ClientFiveResponse struct {
	// placeholder for future response values
}

// Group2ClientSixResponse contains the response from method Group2Client.Six.
type Group2ClientSixResponse struct {
	// placeholder for future response values
}

// Group2ClientTwoResponse contains the response from method Group2Client.Two.
type Group2ClientTwoResponse struct {
	// placeholder for future response values
}
