// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package basicparamsgroup

// BasicExplicitBodyClientSimpleResponse contains the response from method BasicExplicitBodyClient.Simple.
type BasicExplicitBodyClientSimpleResponse struct {
	// placeholder for future response values
}

// BasicImplicitBodyClientSimpleResponse contains the response from method BasicImplicitBodyClient.Simple.
type BasicImplicitBodyClientSimpleResponse struct {
	// placeholder for future response values
}
